name: Python checker

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flake8-docstrings pytest pyqtgraph PyQt5 pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 --show-source .
    - name: Test with pytest
      run: |
        export QT_DEBUG_PLUGINS=1
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt-get install libxcb-icccm4
        sudo apt-get install -y  libglib2.0-0 libxcb-shape0 libxcb-shm0 \
        libxcb-xfixes0 libxcb-randr0 libxcb-image0 \
        libfontconfig1 libgl1-mesa-glx \
        libxi6 libsm6 libxrender1 libpulse0 \
        libxcomposite1 libxslt1.1 libsqlite3-0 \
        libxcb-keysyms1 libxcb-xtest0 libxcb-render-util0 \
        libxcb-xkb1 libxkbcommon-x11-0 libxcb-xinerama0 
        
        
        pytest --doctest-modules --cov=dragon -s
